server:
  port: 9000
spring:
  application:
    name: crypto-trader-admin
  datasource:
    url: ${PSQL_DB_URL}
    username: ${PSQL_USER}
    password: ${PSQL_PW}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    stream:
      defaultBinder: kafka
      bindings:
        # Outbound (publisher example)
        exampleEvent-out-0:
          destination: ct.example.v1
          contentType: application/json

        # Inbound (subscriber example)
        exampleEvent-in-0:
          destination: ct.example.v1
          group: ${spring.application.name}
          contentType: application/json
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          exampleEvent-in-0:
            consumer:
              enableDlq: true
              dlqName: ct.example.v1.DLT
logging:
  level:
    org:
      springframework: INFO
management:
  endpoints.web.exposure.include: health,info
