server:
  port: 8088

spring:
  application:
    name: crypto-trader-console
  config:
      import: aws-secretsmanager:/cryptotrader/dev
  aop:
    proxy-target-class: true

  cloud:
    aws:
      region:
        static: us-east-1
    function:
      definition: consoleRequestsConsumer
    stream:
      enabled: true
      defaultBinder: kafka
      bindings:
        consoleRequestsConsumer-in-0:
          destination: ct.console.requests
          group: crypto-trader-console
          contentType: application/json

        consoleResponses-out-0:
          destination: ct.console.responses
          contentType: application/json

      kafka:
        binder:
          brokers: localhost:9092
          producer-properties:
            linger.ms: 20
            batch.size: 65536
            compression.type: lz4
            acks: 1
          consumer-properties:
            fetch.min.bytes: 1024
            fetch.max.wait.ms: 500
        bindings:
          consoleRequestsConsumer-in-0:
            consumer:
              configuration:
                group.instance.id: console-service-01
                session.timeout.ms: 30000
                heartbeat.interval.ms: 10000
                max.poll.interval.ms: 900000

security:
  jwt:
    jwks-uri: http://localhost:8080/.well-known/jwks.json
    issuers: http://localhost:8080,https://api.cryptotrader.com
    issuer: https://api.cryptotrader.com
    audience: crypto-trader-api

