from enum import Enum


class EpochFocus(Enum):
    INSTANT = 1
    SMALL_VALIDATION = 5
    SMALL_ANALYSIS = 10
    STANDARD_VALIDATION = 20
    REFINED_VALIDATION = 30
    STANDARD_ANALYSIS = 50
    REFINED_ANALYSIS = 75
    DEEP_ANALYSIS = 100
    MOST_ANALYSIS = 150
    COMPLETE_ANALYSIS = 200