agent:
    constraints:
        allowed-hosts:
            - www.example.com
        allowed-tables:
            - public.example_table
        allowed-root: "/example/path"
        ignored-directories:
            - example_directory
        sensitive-file-patterns:
            - "**/file-pattern-*.txt"
