server:
  port: 8089
  address: 127.0.0.1
spring:
  profiles:
    include: constraints
  application:
    name: crypto-trader-agent
  main:
    allow-bean-definition-overriding: false
  datasource:
      url: ${PSQL_DB_URL}
      username: ${PSQL_USER}
      password: ${PSQL_PW}
      generate-unique-name: false
      driver-class-name: org.postgresql.Driver
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false
      hibernate:
          ddl-auto: update
          naming:
              implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  ai:
    mcp:
      server:
        enabled: true
        protocol: STATELESS
        type: SYNC
        name: crypto-trader-agent
        version: 0.0.1
        tool-callback-converter: true
        streamable-http:
          mcp-endpoint: /mcp
          keep-alive-interval: 30s

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.ai.mcp: DEBUG
    org.springframework.ai.mcp.server: DEBUG