server:
    port: 8096
spring:
  config:
    import: aws-secretsmanager:/cryptotrader/dev
  application:
    name: crypto-trader-simulator
  datasource:
    url: ${PSQL_DB_URL}
    username: ${PSQL_USER}
    password: ${PSQL_PW}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  cloud:
    aws:
      region:
        static: us-east-1
    function:
      definition: simulatorConsumer
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          producer-properties:
            linger.ms: 20
            batch.size: 65536
            compression.type: lz4
            acks: 1
          consumer-properties:
            fetch.min.bytes: 1024
            fetch.max.wait.ms: 500
        bindings:
          simulatorConsumer-in-0:
            consumer:
              configuration:
                group.instance.id: simulator-service-01
                session.timeout.ms: 30000
                heartbeat.interval.ms: 10000
                max.poll.interval.ms: 900000
      defaultBinder: kafka
      bindings:
        simulatorConsumer-in-0:
          destination: ct.simulator.requests
          group: crypto-trader-simulator-group
          contentType: application/json
        portfolioSimulationResponses-out-0:
          destination: ct.simulator.responses
          contentType: application/json
