export default {
    printWidth: 100,
    singleQuote: true,
    semi: true,
    tabWidth: 4,
    useTabs: false,
    bracketSpacing: true,
    bracketSameLine: false,
    singleAttributePerLine: false,
    htmlWhitespaceSensitivity: 'ignore',
    trailingComma: 'all',
    arrowParens: 'always',
    endOfLine: 'lf',
    insertPragma: false,
    requirePragma: false,
    plugins: [
        'prettier-plugin-organize-attributes',
        // '@ianvs/prettier-plugin-sort-imports',
    ],
    attributeGroups: [
        '$ANGULAR_STRUCTURAL_DIRECTIVE',
        '$ANGULAR_ELEMENT_REF',
        '$ANGULAR_INPUT',
        '$ANGULAR_TWO_WAY_BINDING',
        '$ANGULAR_OUTPUT',
        '$ANGULAR_ANIMATION',
        '$ANGULAR_ANIMATION_INPUT',
        '$DEFAULT',
    ],
    /*
    importOrder: [
        '^@angular/(.*)$',
        '<THIRD_PARTY_MODULES>',
        '',
        '^@theoliverlear/(.*)$',
        '^@app/(.*)$',
        '^@services/(.*)$',
        '^@assets/(.*)$',
        '^@components/(.*)$',
        '^@environments/(.*)$',
        '^@ws/(.*)$',
        '^@http/(.*)$',
        '^@ui/(.*)$',
        '^@auth/(.*)$',
        '^@guards/(.*)$',
        '^@models/(.*)$',
        '',
        '^[./]',
    ],
    */
    // importOrderSeparation: true,
    // importOrderSortSpecifiers: true,
    // importOrderParserPlugins: ['typescript', 'decorators-legacy'],
    // importOrderTypeScriptVersion: '5.0.0',
    overrides: [
        {
            files: ['*.html'],
            options: {
                parser: 'angular',
            },
        },
    ],
};
