server:
  port: 8093

spring:
  config:
    import: aws-secretsmanager:/cryptotrader/dev
  application:
    name: crypto-trader-logging
  datasource:
    url: ${PSQL_DB_URL}
    username: ${PSQL_USER}
    password: ${PSQL_PW}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cloud:
    aws:
      region:
        static: us-east-1
    function:
      definition: frontendLogsConsumer
    stream:
      enabled: true
      defaultBinder: kafka
      bindings:
        frontendLogsConsumer-in-0:
          destination: ct.logging.frontend.v1
          group: crypto-trader-logging
          contentType: application/json
      kafka:
        binder:
          brokers: localhost:9092
          producer-properties:
            linger.ms: 20
            batch.size: 65536
            compression.type: lz4
            acks: 1
          consumer-properties:
            fetch.min.bytes: 1024
            fetch.max.wait.ms: 500
        bindings:
          frontendLogsConsumer-in-0:
            consumer:
              enableDlq: true
              dlqName: ct.logging.frontend.v1.DLT
              configuration:
                group.instance.id: logging-service-01
                session.timeout.ms: 30000
                heartbeat.interval.ms: 10000
                max.poll.interval.ms: 900000

logging:
  level:
    org.springframework: INFO
