server:
  port: 8087

logging:
  level:
    org.springframework.mail: DEBUG
    org.eclipse.angus.mail: DEBUG

spring:
  application:
    name: crypto-trader-contact
  mail:
    host: smtp.mail.us-east-1.awsapps.com
    port: 465
    username: contact@sscryptotrader.com
    password: ${WORKMAIL_PW}
    properties:
      mail:
        smtp:
          from: contact@sscryptotrader.com
          auth: true
          ssl:
            enable: true
    default-encoding: UTF-8
  cloud:
    function:
      definition: userRegistered
      sanitization:
        enabled: false
    stream:
      function:
        sanitizing:
          enabled: false
      defaultBinder: kafka
      bindings:
        userRegistered-in-0:
          destination: ct.user.registered.v1
          group: ${spring.application.name}
          contentType: application/json
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          userRegistered-in-0:
            consumer:
              enableDlq: true
              dlqName: ct.user.registered.v1.DLT
  function:
    sanitizing:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info