server:
  port: 8087
logging:
  level.org.springframework.mail: DEBUG
  level.org.eclipse.angus.mail: DEBUG
spring:
  application:
    name: crypto-trader-contact
  mail:
    host: smtp.mail.us-east-1.awsapps.com
    port: 465
    username: contact@sscryptotrader.com
    password: ${WORKMAIL_PW}
    properties:
      mail:
        smtp:
          from: contact@sscryptotrader.com
          auth: true
          ssl:
            enable: true
    default-encoding: UTF-8
  cloud:
    stream:
      defaultBinder: kafka
      bindings:
        # Outbound (publisher example)
        exampleEvent-out-0:
          destination: ct.example.v1
          contentType: application/json

        # Inbound (subscriber example)
        userRegistered-in-0:
          destination: ct.user.registered.v1
          group: ${spring.application.name}
          contentType: application/json
        exampleEvent-in-0:
          destination: ct.example.v1
          group: ${spring.application.name}
          contentType: application/json
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          exampleEvent-in-0:
            consumer:
              enableDlq: true
              dlqName: ct.example.v1.DLT

management:
  endpoints.web.exposure.include: health,info