server:
  port: ${SERVER_PORT:18080}

spring:
  devtools:
    restart:
      enabled: false
    add-properties: false
  main:
    web-application-type: servlet
    lazy-initialization: false
  task:
    scheduling:
      enabled: false
  datasource:
    url: jdbc:h2:mem:docs;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false;CASE_INSENSITIVE_IDENTIFIERS=true
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: false
  flyway:
    enabled: false
  liquibase:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  cloud:
    stream:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
