cryptotrader:
  api:
    cors:
      enabled: true
      allowed-origins: http://localhost:4200
      allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
      allowed-headers: "*"
      exposed-headers: Location,Link
      allow-credentials: true
    security:
      enabled: true
