site_name: Crypto Trader Docs
site_url: https://theoliverlear.github.io/Crypto-Trader/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Guides:
      - Guides: guides/index.md
  - CT API: api/index.md
  - Data API: data/index.md
  - Website:
      - README: reference/Website/README.md
      - Complete Docs: reference/Website/api/index.html
  - References:
    - Admin:
      - README: reference/Admin/README.md
      - Complete Docs: reference/Admin/api/index.html
    - Agent:
      - README: reference/Agent/README.md
      - Complete Docs: reference/Agent/api/index.html
    - Analysis:
      - README: reference/Analysis/README.md
    - Api:
      - README: reference/Api/README.md
      - Complete Docs: reference/Api/api/index.html
    - Assets:
      - README: reference/Assets/README.md
      - Complete Docs: reference/Assets/api/index.html
    - Chat:
      - README: reference/Chat/README.md
      - Complete Docs: reference/Chat/api/index.html
    - Console:
      - README: reference/Console/README.md
      - Complete Docs: reference/Console/api/index.html
    - Contact:
      - README: reference/Contact/README.md
      - Complete Docs: reference/Contact/api/index.html
    - Data:
      - README: reference/Data/README.md
      - Complete Docs: reference/Data/api/index.html
    - Engine:
      - README: reference/Engine/README.md
      - Complete Docs: reference/Engine/api/index.html
    - Health:
      - README: reference/Health/README.md
      - Complete Docs: reference/Health/api/index.html
    - Logging:
      - README: reference/Logging/README.md
      - Complete Docs: reference/Logging/api/index.html
    - Mobile:
      - README: reference/Mobile/README.md
    - Security:
      - README: reference/Security/README.md
      - Complete Docs: reference/Security/api/index.html
    - Simulator:
      - README: reference/Simulator/README.md
      - Complete Docs: reference/Simulator/api/index.html
    - Testing:
      - README: reference/Testing/README.md
      - Complete Docs: reference/Testing/api/index.html
    - Transactions:
      - README: reference/Transactions/README.md
      - Complete Docs: reference/Transactions/api/index.html
    - Version:
      - README: reference/Version/README.md
      - Complete Docs: reference/Version/api/index.html
  - Library:
    - Overview: library/index.md
    - Library:
      - README: library/README.md
    - Admin-Library:
      - README: library/Admin-Library/README.md
    - Admin-Events:
      - README: library/Admin-Library/Admin-Events/README.md
      - Complete Docs: library/Admin-Library/Admin-Events/api/index.html
    - Admin-Models:
      - README: library/Admin-Library/Admin-Models/README.md
      - Complete Docs: library/Admin-Library/Admin-Models/api/index.html
    - Agent-Library:
      - README: library/Agent-Library/README.md
    - Agent-Communication:
      - README: library/Agent-Library/Agent-Communication/README.md
      - Complete Docs: library/Agent-Library/Agent-Communication/api/index.html
    - Agent-Components:
      - README: library/Agent-Library/Agent-Components/README.md
      - Complete Docs: library/Agent-Library/Agent-Components/api/index.html
    - Agent-Config:
      - README: library/Agent-Library/Agent-Config/README.md
      - Complete Docs: library/Agent-Library/Agent-Config/api/index.html
    - Agent-Infrastructure:
      - README: library/Agent-Library/Agent-Infrastructure/README.md
      - Complete Docs: library/Agent-Library/Agent-Infrastructure/api/index.html
    - Agent-Models:
      - README: library/Agent-Library/Agent-Models/README.md
      - Complete Docs: library/Agent-Library/Agent-Models/api/index.html
    - Api-Library:
      - README: library/Api-Library/README.md
    - Api-Communication:
      - README: library/Api-Library/Api-Communication/README.md
      - Complete Docs: library/Api-Library/Api-Communication/api/index.html
    - Api-Components:
      - README: library/Api-Library/Api-Components/README.md
      - Complete Docs: library/Api-Library/Api-Components/api/index.html
    - Api-Config:
      - README: library/Api-Library/Api-Config/README.md
      - Complete Docs: library/Api-Library/Api-Config/api/index.html
    - Api-Events:
      - README: library/Api-Library/Api-Events/README.md
      - Complete Docs: library/Api-Library/Api-Events/api/index.html
    - Api-Extensions:
      - README: library/Api-Library/Api-Extensions/README.md
      - Complete Docs: library/Api-Library/Api-Extensions/api/index.html
    - Api-Infrastructure:
      - README: library/Api-Library/Api-Infrastructure/README.md
      - Complete Docs: library/Api-Library/Api-Infrastructure/api/index.html
    - Api-Models:
      - README: library/Api-Library/Api-Models/README.md
      - Complete Docs: library/Api-Library/Api-Models/api/index.html
    - Api-Repositories:
      - README: library/Api-Library/Api-Repositories/README.md
      - Complete Docs: library/Api-Library/Api-Repositories/api/index.html
    - Api-Scripts:
      - README: library/Api-Library/Api-Scripts/README.md
      - Complete Docs: library/Api-Library/Api-Scripts/api/index.html
    - Api-Services:
      - README: library/Api-Library/Api-Services/README.md
      - Complete Docs: library/Api-Library/Api-Services/api/index.html
    - Chat-Library:
      - README: library/Chat-Library/README.md
    - Chat-Communication:
      - README: library/Chat-Library/Chat-Communication/README.md
      - Complete Docs: library/Chat-Library/Chat-Communication/api/index.html
    - Chat-Components:
      - README: library/Chat-Library/Chat-Components/README.md
      - Complete Docs: library/Chat-Library/Chat-Components/api/index.html
    - Chat-Config:
      - README: library/Chat-Library/Chat-Config/README.md
      - Complete Docs: library/Chat-Library/Chat-Config/api/index.html
    - Chat-Events:
      - README: library/Chat-Library/Chat-Events/README.md
      - Complete Docs: library/Chat-Library/Chat-Events/api/index.html
    - Chat-Models:
      - README: library/Chat-Library/Chat-Models/README.md
      - Complete Docs: library/Chat-Library/Chat-Models/api/index.html
    - Chat-Repositories:
      - README: library/Chat-Library/Chat-Repositories/README.md
      - Complete Docs: library/Chat-Library/Chat-Repositories/api/index.html
    - Chat-Services:
      - README: library/Chat-Library/Chat-Services/README.md
      - Complete Docs: library/Chat-Library/Chat-Services/api/index.html
    - Console-Library:
      - README: library/Console-Library/README.md
    - Console-Communication:
      - README: library/Console-Library/Console-Communication/README.md
      - Complete Docs: library/Console-Library/Console-Communication/api/index.html
    - Console-Components:
      - README: library/Console-Library/Console-Components/README.md
      - Complete Docs: library/Console-Library/Console-Components/api/index.html
    - Console-Events:
      - README: library/Console-Library/Console-Events/README.md
      - Complete Docs: library/Console-Library/Console-Events/api/index.html
    - Console-Models:
      - README: library/Console-Library/Console-Models/README.md
      - Complete Docs: library/Console-Library/Console-Models/api/index.html
    - Console-Services:
      - README: library/Console-Library/Console-Services/README.md
      - Complete Docs: library/Console-Library/Console-Services/api/index.html
    - Contact-Library:
      - README: library/Contact-Library/README.md
    - Contact-Events:
      - README: library/Contact-Library/Contact-Events/README.md
      - Complete Docs: library/Contact-Library/Contact-Events/api/index.html
    - Contact-Models:
      - README: library/Contact-Library/Contact-Models/README.md
      - Complete Docs: library/Contact-Library/Contact-Models/api/index.html
    - Contact-Repositories:
      - README: library/Contact-Library/Contact-Repositories/README.md
      - Complete Docs: library/Contact-Library/Contact-Repositories/api/index.html
    - Data-Library:
      - README: library/Data-Library/README.md
    - Data-Communication:
      - README: library/Data-Library/Data-Communication/README.md
      - Complete Docs: library/Data-Library/Data-Communication/api/index.html
    - Data-Components:
      - README: library/Data-Library/Data-Components/README.md
      - Complete Docs: library/Data-Library/Data-Components/api/index.html
    - Data-Models:
      - README: library/Data-Library/Data-Models/README.md
      - Complete Docs: library/Data-Library/Data-Models/api/index.html
    - Data-Repositories:
      - README: library/Data-Library/Data-Repositories/README.md
      - Complete Docs: library/Data-Library/Data-Repositories/api/index.html
    - Data-Services:
      - README: library/Data-Library/Data-Services/README.md
      - Complete Docs: library/Data-Library/Data-Services/api/index.html
    - Desktop-Library:
      - README: library/Desktop-Library/README.md
    - Desktop-Components:
      - README: library/Desktop-Library/Desktop-Components/README.md
      - Complete Docs: library/Desktop-Library/Desktop-Components/api/index.html
    - Engine-Library:
      - README: library/Engine-Library/README.md
    - Engine-Services:
      - README: library/Engine-Library/Engine-Services/README.md
      - Complete Docs: library/Engine-Library/Engine-Services/api/index.html
    - Externals-Library:
      - README: library/Externals-Library/README.md
    - Health-Library:
      - README: library/Health-Library/README.md
    - Health-Communication:
      - README: library/Health-Library/Health-Communication/README.md
      - Complete Docs: library/Health-Library/Health-Communication/api/index.html
    - Health-Components:
      - README: library/Health-Library/Health-Components/README.md
      - Complete Docs: library/Health-Library/Health-Components/api/index.html
    - Health-Config:
      - README: library/Health-Library/Health-Config/README.md
      - Complete Docs: library/Health-Library/Health-Config/api/index.html
    - Health-Models:
      - README: library/Health-Library/Health-Models/README.md
      - Complete Docs: library/Health-Library/Health-Models/api/index.html
    - Health-Repositories:
      - README: library/Health-Library/Health-Repositories/README.md
      - Complete Docs: library/Health-Library/Health-Repositories/api/index.html
    - Health-Services:
      - README: library/Health-Library/Health-Services/README.md
      - Complete Docs: library/Health-Library/Health-Services/api/index.html
    - Logging-Library:
      - README: library/Logging-Library/README.md
    - Logging-Communication:
      - README: library/Logging-Library/Logging-Communication/README.md
      - Complete Docs: library/Logging-Library/Logging-Communication/api/index.html
    - Logging-Config:
      - README: library/Logging-Library/Logging-Config/README.md
      - Complete Docs: library/Logging-Library/Logging-Config/api/index.html
    - Logging-Events:
      - README: library/Logging-Library/Logging-Events/README.md
      - Complete Docs: library/Logging-Library/Logging-Events/api/index.html
    - Logging-Infrastructure:
      - README: library/Logging-Library/Logging-Infrastructure/README.md
      - Complete Docs: library/Logging-Library/Logging-Infrastructure/api/index.html
    - Logging-Models:
      - README: library/Logging-Library/Logging-Models/README.md
      - Complete Docs: library/Logging-Library/Logging-Models/api/index.html
    - Logging-Repositories:
      - README: library/Logging-Library/Logging-Repositories/README.md
      - Complete Docs: library/Logging-Library/Logging-Repositories/api/index.html
    - Logging-Services:
      - README: library/Logging-Library/Logging-Services/README.md
      - Complete Docs: library/Logging-Library/Logging-Services/api/index.html
    - Security-Library:
      - README: library/Security-Library/README.md
    - Security-Config:
      - README: library/Security-Library/Security-Config/README.md
      - Complete Docs: library/Security-Library/Security-Config/api/index.html
    - Security-Events:
      - README: library/Security-Library/Security-Events/README.md
      - Complete Docs: library/Security-Library/Security-Events/api/index.html
    - Security-Infrastructure:
      - README: library/Security-Library/Security-Infrastructure/README.md
      - Complete Docs: library/Security-Library/Security-Infrastructure/api/index.html
    - Security-Models:
      - README: library/Security-Library/Security-Models/README.md
      - Complete Docs: library/Security-Library/Security-Models/api/index.html
    - Security-Repositories:
      - README: library/Security-Library/Security-Repositories/README.md
      - Complete Docs: library/Security-Library/Security-Repositories/api/index.html
    - Security-Services:
      - README: library/Security-Library/Security-Services/README.md
      - Complete Docs: library/Security-Library/Security-Services/api/index.html
    - Universal-Library:
      - README: library/Universal-Library/README.md
    - Universal-Components:
      - README: library/Universal-Library/Universal-Components/README.md
      - Complete Docs: library/Universal-Library/Universal-Components/api/index.html
    - Universal-Config:
      - README: library/Universal-Library/Universal-Config/README.md
      - Complete Docs: library/Universal-Library/Universal-Config/api/index.html
    - Universal-Extensions:
      - README: library/Universal-Library/Universal-Extensions/README.md
      - Complete Docs: library/Universal-Library/Universal-Extensions/api/index.html
    - Universal-Models:
      - README: library/Universal-Library/Universal-Models/README.md
      - Complete Docs: library/Universal-Library/Universal-Models/api/index.html
    - Version-Library:
      - README: library/Version-Library/README.md
    - Version-Models:
      - README: library/Version-Library/Version-Models/README.md
      - Complete Docs: library/Version-Library/Version-Models/api/index.html
  - Coverage: coverage/index.html