site_name: Crypto Trader Docs
site_url: https://theoliverlear.github.io/Crypto-Trader/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Guides:
      - Guides: guides/index.md
  - CT API: api/index.md
  - Data API: data/index.md
  - Engine API: engine/index.md
  - References:
    - Api:
      - README: reference/Api/README.md
      - Complete Docs: reference/Api/api/index.html
    - Admin:
      - README: reference/Admin/README.md
      - Complete Docs: reference/Admin/api/index.html
    - Assets:
      - README: reference/Assets/README.md
      - Complete Docs: reference/Assets/api/index.html
    - Data:
      - README: reference/Data/README.md
      - Complete Docs: reference/Data/api/index.html
    - Engine:
      - README: reference/Engine/README.md
      - Complete Docs: reference/Engine/api/index.html
    - Library:
      - README: reference/Library/README.md
      - Complete Docs: reference/Library/api/index.html
    - Logging:
      - README: reference/Logging/README.md
      - Complete Docs: reference/Logging/api/index.html
    - Testing:
      - README: reference/Testing/README.md
      - Complete Docs: reference/Testing/api/index.html
    - Version:
      - README: reference/Version/README.md
      - Complete Docs: reference/Version/api/index.html
  - Coverage:
    - Overall: coverage/index.html
    - Api: coverage/crypto-trader-api/index.html
    - Admin: coverage/crypto-trader-admin/index.html
    - Assets: coverage/crypto-trader-assets/index.html
    - Data: coverage/crypto-trader-data/index.html
    - Engine: coverage/crypto-trader-engine/index.html
    - Logging: coverage/crypto-trader-logging/index.html
    - Testing: coverage/crypto-trader-testing/index.html
    - Version: coverage/crypto-trader-version/index.html
    - Api-Services: coverage/api-services/index.html
    - Api-Repositories: coverage/api-repositories/index.html
    - Api-Components: coverage/api-components/index.html
    - Api-Communication: coverage/api-communication/index.html
    - Api-Config: coverage/api-config/index.html
    - Api-Models: coverage/api-models/index.html
    