site_name: Crypto Trader Docs
site_url: https://theoliverlear.github.io/Crypto-Trader/
theme:
  name: material
  features:
    - navigation.instant
    - content.code.copy
    - search.highlight
markdown_extensions:
  - admonition
  - toc:
      permalink: true
nav:
  - Home: index.md
  - API: crypto-trader-api.md
