# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy modules (skip if version exists)
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
        run: |
          set -e
          echo "Discovering modules..."
          poms=$(git ls-files '**/pom.xml')
          for pom in $poms; do
            PACK=$(mvn -q -DforceStdout -f "$pom" help:evaluate -Dexpression=project.packaging)
            if [ "$PACK" = "pom" ]; then
              continue
            fi
            G=$(mvn -q -DforceStdout -f "$pom" help:evaluate -Dexpression=project.groupId)
            A=$(mvn -q -DforceStdout -f "$pom" help:evaluate -Dexpression=project.artifactId)
            V=$(mvn -q -DforceStdout -f "$pom" help:evaluate -Dexpression=project.version)
            GP=${G//./\/}
            URL="https://maven.pkg.github.com/${REPO}/${GP}/${A}/${V}/${A}-${V}.pom"
            echo "Checking $A:$V at $URL"
            code=$(curl -L -s -o /dev/null -w "%{http_code}" -u "${{ github.actor }}:${GITHUB_TOKEN}" "$URL")
            if [ "$code" = "200" ]; then
              echo "Artifact already exists (HTTP 200). Skipping deploy for $A:$V"
              continue
            fi
            if [ "$code" = "401" ] || [ "$code" = "403" ]; then
              echo "Auth check issue for $A:$V (HTTP $code). Proceeding with deploy to avoid false skip."
            fi
            echo "Deploying $A:$V from $pom"
            mvn -B -f "$pom" -DskipTests=true deploy -s "$GITHUB_WORKSPACE/settings.xml"
          done
