name: Maven Publish

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: theoliverlear/Sigwarth-Software-Suite/.github/workflows/maven-package.yml@d024bd332b95e4640e0838d69fddde6a7cfc549a
    with:
      java-version: '23'
      distribution: temurin
    secrets: inherit